# Generated by Django 4.0 on 2022-08-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celery_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(default='Some String', max_length=1000000),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='Some String', max_length=255),
        ),
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='celery_application.author'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='text',
            field=models.CharField(default='Some String', max_length=255),
        ),
    ]
