# Generated by Django 4.0 on 2022-08-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_application', '0002_author_description_author_name_quotes_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='text',
            new_name='texts',
        ),
    ]
